# Generated by Django 4.2.5 on 2023-10-21 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('calories', models.IntegerField()),
                ('fat', models.IntegerField()),
                ('carbohydrates', models.IntegerField()),
                ('protein', models.IntegerField()),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('ingredients', models.JSONField()),
                ('servings', models.IntegerField(default=0)),
            ],
        ),
    ]
